### ISSUE TITLE
audio chunks are not encrypted

### ISSUE THREAD

**Issue by rajubabannavar** [WowzaMediaSystems/wse-plugin-multitrackvod#1]
When I configure this module with my Wowza server and stream an asset with the multiple audio tracks, Wowza is only encrypting the video chunks and audio chunks are not encrypted. Is this the expected behaviour of Wowza? Do I need to set any specific flag to enable audio chunk encryption?

Please find the sample SMIL configuration in the attached file.

[sample.txt](https://github.com/WowzaMediaSystems/wse-plugin-multitrackvod/files/1285159/sample.txt)

**Comment by rogerlittin** [comment]
Hi,

I tested the module using your smil file and sample.mp4 that comes with the server and it appears to work as expected. In the returned HLS manifest, I get a video only chunklist link as well as the audio only chunklist link.

```
curl http://192.168.1.50:1935/multitrack/smil:multitrack.smil/playlist.m3u8
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=2500000,RESOLUTION=1920x1080,AUDIO="audio_2500"
chunklist_w1313000202_b2500000_vo.m3u8
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio_2500",LANGUAGE="en",NAME="emb_English",DEFAULT=YES,AUTOSELECT=YES,URI="chunklist_w1313000202_b132000_ao_slen_t64ZW1iX0VuZ2xpc2g=.m3u8"
```

**Comment by rajubabannavar** [comment]
Hi Roger,
When you down the video and audio chunklist, you will see that only video chunklist file has the key url entry. And you can go ahead and download the video and audio ts chunks. Where in video chunks cannot be played by VLC but audio chunks can.

**Comment by rogerlittin** [comment]
Hi,

Now I understand. It sounds like a bug with encryption rather than the multitrack vod module. Can you please open a support ticket and send us the smil file and key file that you are using along with the conf & logs folders.

Thanks,

Roger.

**Comment by rajubabannavar** [comment]
Hi Roger,
I have opened a support ticket with Wowza and provided required details.

**Comment by akeller** [comment]
Stale, closing.
